package appdev;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
//import static menu.ey;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    public employee() {
        initComponents();
        this.setLocationRelativeTo(this);
        showTableData();
        try{
     String query4 ="SELECT * FROM mydata (pos,full_name) VALUES (?,?)";
     con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
     ps = con.prepareStatement(query4);
        ps.setString(1,Register.pos.getText());
        ps.setString(2,Register.firstname.getText()+(" ")+ Register.middlename.getText()+(" ")+Register.lastname.getText());
        ps.executeQuery();
     
     }catch(Exception e){
        //JOptionPane.showMessageDialog(null,"Server not connected","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    
    }
    public void showTableData(){
         try{
      String query5="SELECT * FROM mydata";
         con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root",""); 
         ps = con.prepareStatement(query5);
         rs = ps.executeQuery();
         table2.setModel(DbUtils.resultSetToTableModel(rs) );
         }catch(Exception e ){
           JOptionPane.showMessageDialog(null,e);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        pos1 = new javax.swing.JLabel();
        cpos = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        cname1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdev/hey.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 180, 160);

        jLabel5.setText("First Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 90, 80, 16);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 130, 0, 234);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("EMPLOYEE'S PROFILE");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 20, 280, 29);

        jLabel15.setText("Positon:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(260, 130, 80, 16);

        b3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b3.setText("LOG OUT");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(460, 330, 140, 25);

        pos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pos1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pos1);
        pos1.setBounds(340, 130, 90, 20);

        cpos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cpos.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.add(cpos);
        cpos.setBounds(90, 200, 140, 20);
        jPanel1.add(cid);
        cid.setBounds(270, 170, 30, 30);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(90, 280, 300, 100);

        cname1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cname1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(cname1);
        cname1.setBounds(340, 90, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
  
    this.dispose();
    login1 open = new login1();
    open.setVisible(true);



    }//GEN-LAST:event_b3ActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked

int e=table2.getSelectedRow();
        TableModel display=table2.getModel();
        cid.setText(display.getValueAt(e,0).toString()); 
        pos1.setText(display.getValueAt(e,1).toString());  
        cname1.setText(display.getValueAt(e,2).toString());


    }//GEN-LAST:event_table2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.JTextField cid;
    private javax.swing.JLabel cname1;
    private javax.swing.JLabel cpos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pos1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}

