package appdev;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.awt.Color.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class login1 extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    public login1() {
        initComponents();
        this.setLocationRelativeTo(this);
        cov.setBackground(new Color(0,0,0,100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos = new javax.swing.JLabel();
        pos1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        cov = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        pos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pos.setForeground(new java.awt.Color(255, 255, 255));

        pos1.setEditable(true);
        pos1.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        pos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TYPE OF USERS", "HR", "EMPLOYEE" }));
        pos1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pos1ItemStateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        cov.setBackground(new java.awt.Color(153, 204, 255));

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD:");

        username.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri Light", 1, 15)); // NOI18N
        jButton2.setText("cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout covLayout = new javax.swing.GroupLayout(cov);
        cov.setLayout(covLayout);
        covLayout.setHorizontalGroup(
            covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(covLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(79, 79, 79)
                .addComponent(jButton2)
                .addGap(199, 199, 199))
            .addGroup(covLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(covLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(covLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        covLayout.setVerticalGroup(
            covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(covLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(covLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jPanel1.add(cov);
        cov.setBounds(0, 30, 660, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String user=username.getText();
   String pass=password.getText();
   
         
//        if(user.equalsIgnoreCase("renee")&& pass.equalsIgnoreCase("casicas")){
//            JOptionPane.showMessageDialog(null,"Login as HR Successfully");
//             this.dispose();
//        menu open=new menu();
//        open.setVisible(true);
//        }else if(){
//                JOptionPane.showMessageDialog(null,"ERROR","UNSUCESSFULLL", JOptionPane.ERROR_MESSAGE);
//                }
 


try{  
 
          String query1="SELECT * FROM mydata WHERE username=? and pass=?";
          con=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
          ps=con.prepareStatement(query1);
          ps.setString(1,username.getText());   
          ps.setString(2,password.getText());
          rs=ps.executeQuery();
          if (username.getText().equals("") ||password.getText().equals("")){
          JOptionPane.showMessageDialog(null, "ERROR!","ERROR",JOptionPane.ERROR_MESSAGE);
          }else if(user.equalsIgnoreCase("admin")&& pass.equalsIgnoreCase("john")){
          JOptionPane.showMessageDialog(null,"Login as HR Successfully");
           this.dispose();
           menu open=new menu();
           open.setVisible(true);
          }else if (rs.next()){
              this.dispose();
              employee open=new employee();
              open.setVisible(true);
              
//              JOptionPane.showMessageDialog(null,"welcome"+rs.getString("reg_Uname"));
          }else{
                 JOptionPane.showMessageDialog(null,"Account not found!");
          }
          }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Sorry you are not connected!");
      }
              
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pos1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pos1ItemStateChanged
       
    }//GEN-LAST:event_pos1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cov;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPasswordField password;
    private javax.swing.JLabel pos;
    private javax.swing.JComboBox<String> pos1;
    public static javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
