package appdev;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.awt.Color.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author User
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    public menu() {
        initComponents();
        this.setLocationRelativeTo(this);
        jButton1.setVisible(false);
        apos.setVisible(false);
        cgend.setVisible(false);
        showTableData();
    
     try{
     String queryaa ="SELECT * FROM mydata (pos,full_name,gender,date,age,username,pass) VALUES (?,?,?,?,?,?,?)";
     con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
     ps = con.prepareStatement(queryaa);
        ps.setString(1,Register.pos.getText());
        ps.setString(2,Register.firstname.getText()+(" ")+ Register.middlename.getText()+(" ")+Register.lastname.getText());
        ps.setString(3,Register.GENDER.getText());
        ps.setString(4,Register.month.getText() +(" ")+ Register.day.getText() +(" ")+ Register.year1.getText());
        ps.setString(5,Register.age1.getText());
        ps.setString(6,Register.username1.getText());
        ps.setString(7,Register.password1.getText());
        ps.executeUpdate();
     }catch(Exception e){
        //JOptionPane.showMessageDialog(null,"Server not connected","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     *
     */
    public void showTableData(){
         try{
      String query3="SELECT * FROM mydata";
         con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root",""); 
         ps = con.prepareStatement(query3);
         rs = ps.executeQuery();
         ey.setModel(DbUtils.resultSetToTableModel(rs) );
         }catch(Exception e ){
           JOptionPane.showMessageDialog(null,e);
       }
   }
     
      
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ey = new javax.swing.JTable();
        gpass = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        eage = new javax.swing.JTextField();
        dbirth = new javax.swing.JTextField();
        fuser = new javax.swing.JTextField();
        jComboBoxgen = new javax.swing.JComboBox<>();
        cgend = new javax.swing.JLabel();
        jComboBoxpos = new javax.swing.JComboBox<>();
        apos = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        upup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jButton1.setText("EDIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 280, 80, 31);

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jButton8.setText("ADD");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(30, 190, 65, 31);

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jButton9.setText("PAYSLIP");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(30, 230, 100, 31);

        jButton10.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jButton10.setText("LOG OUT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(890, 350, 100, 31);

        ey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ey);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(220, 10, 870, 110);

        gpass.setText("password");
        gpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpassActionPerformed(evt);
            }
        });
        jPanel1.add(gpass);
        gpass.setBounds(360, 230, 150, 30);

        bname.setText("Full Name");
        jPanel1.add(bname);
        bname.setBounds(200, 180, 150, 30);

        eage.setText("age");
        jPanel1.add(eage);
        eage.setBounds(200, 280, 30, 30);

        dbirth.setText("Birth");
        jPanel1.add(dbirth);
        dbirth.setBounds(200, 230, 150, 30);

        fuser.setText("username");
        fuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuserActionPerformed(evt);
            }
        });
        jPanel1.add(fuser);
        fuser.setBounds(360, 180, 150, 30);

        jComboBoxgen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female" }));
        jComboBoxgen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxgenItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxgen);
        jComboBoxgen.setBounds(250, 280, 80, 30);

        cgend.setForeground(new java.awt.Color(255, 255, 255));
        cgend.setText("gend");
        jPanel1.add(cgend);
        cgend.setBounds(250, 320, 70, 30);

        jComboBoxpos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POSITION", "Service Crew", "Cook", "Cashier" }));
        jComboBoxpos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxposItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxpos);
        jComboBoxpos.setBounds(340, 280, 180, 30);

        apos.setForeground(new java.awt.Color(255, 255, 255));
        apos.setText("posi");
        jPanel1.add(apos);
        apos.setBounds(350, 320, 110, 30);

        h.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h.setText("ID");
        jPanel1.add(h);
        h.setBounds(200, 140, 30, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(560, 280, 110, 25);

        upup.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        upup.setText("UPDATE");
        upup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upupActionPerformed(evt);
            }
        });
        jPanel1.add(upup);
        upup.setBounds(560, 230, 110, 25);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("password");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(360, 260, 60, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(360, 210, 60, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("full name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 210, 60, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("age");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 330, 30, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("date of birth");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 260, 110, 16);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        jPanel1.add(search);
        search.setBounds(30, 50, 160, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Register rloh= new Register();
        rloh.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        payslip_1 open=new payslip_1();
        open.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
        login1 open=new login1();
        open.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void gpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpassActionPerformed

    private void fuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuserActionPerformed

    private void eyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyMouseClicked

int i=ey.getSelectedRow();
        TableModel display=ey.getModel();
        h.setText(display.getValueAt(i,0).toString()); 
        apos.setText(display.getValueAt(i,1).toString());  
        bname.setText(display.getValueAt(i,2).toString());
        cgend.setText(display.getValueAt(i,3).toString());
        dbirth.setText(display.getValueAt(i,4).toString());
        eage.setText(display.getValueAt(i,5).toString());
        fuser.setText(display.getValueAt(i,6).toString());
        gpass.setText(display.getValueAt(i,7).toString());



    }//GEN-LAST:event_eyMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

try{
        apos.setText("");
        bname.setText("");
        cgend.setText("");
        dbirth.setText("");
        eage.setText("");
        fuser.setText("");
        gpass.setText("");
      
        String query_update2="DELETE FROM mydata WHERE pos_id=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
        ps=con.prepareStatement(query_update2);
        ps.setString(1,h.getText());    
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(null,"Successfully deleted !");
        showTableData();
          
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Sorry you are not connected to database!");
        

     }





    }//GEN-LAST:event_jButton2ActionPerformed

    private void upupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upupActionPerformed
try{
        String query_update="UPDATE mydata SET pos=?, full_name=?, gender=?, date=?, age=?, username=?, pass=? WHERE pos_id=?";
        con=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
        ps=con.prepareStatement(query_update);
        ps.setString(1,apos.getText());
        ps.setString(2,bname.getText());
        ps.setString(3,cgend.getText());
        ps.setString(4,dbirth.getText());
        ps.setString(5,eage.getText());
        ps.setString(6,fuser.getText());
        ps.setString(7,gpass.getText());
        ps.setString(8,h.getText());    
        ps.executeUpdate();
        
        JOptionPane.showMessageDialog(null,"Successfully Updated !");
        showTableData();
          
        apos.setText("");
        bname.setText("");
        cgend.setText("");
        dbirth.setText("");
        eage.setText("");
        fuser.setText("");
        gpass.setText("");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Sorry you are not connected to database!");
        
        
        
        
     }    }//GEN-LAST:event_upupActionPerformed

    private void jComboBoxgenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxgenItemStateChanged
String qw = jComboBoxgen.getSelectedItem().toString();
        cgend.setText(qw);




    }//GEN-LAST:event_jComboBoxgenItemStateChanged

    private void jComboBoxposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxposItemStateChanged

String wq = jComboBoxpos.getSelectedItem().toString();
        apos.setText(wq);


    }//GEN-LAST:event_jComboBoxposItemStateChanged

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        try{
            String select_query = "SELECT * FROM `mydata` WHERE full_name=?";
            con=DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            ps=con.prepareStatement(select_query);
            ps.setString(1,search.getText());
            rs=ps.executeQuery();

            if(rs.next()){
                String add1 = rs.getString("pos");
                apos.setText(add1);
                String add2 = rs.getString("full_name");
                bname.setText(add2);
                String add3 = rs.getString("gender");
                cgend.setText(add3);
                String add4 = rs.getString("date");
                dbirth.setText(add4);
                String add5 = rs.getString("age");
                eage.setText(add5);
                String add6 = rs.getString("username");
                fuser.setText(add6);
                String add7 = rs.getString("pass");
                gpass.setText(add7);
                String add8 = rs.getString("pos_id");
                h.setText(add8);

                apos.setVisible(true);
                cgend.setVisible(true);

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Sorry you are not connected to database!");
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apos;
    private javax.swing.JTextField bname;
    private javax.swing.JLabel cgend;
    private javax.swing.JTextField dbirth;
    private javax.swing.JTextField eage;
    public static javax.swing.JTable ey;
    private javax.swing.JTextField fuser;
    private javax.swing.JTextField gpass;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBoxgen;
    private javax.swing.JComboBox<String> jComboBoxpos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private javax.swing.JButton upup;
    // End of variables declaration//GEN-END:variables
}

