package appdev;


import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.awt.*;
import java.awt.Color.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author User
 */
public class payslip_1 extends javax.swing.JFrame {

    /**
     * Creates new form payslip
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public payslip_1() {
        initComponents();
       jLabel1.setBackground(new Color(0,0,0,100));
       a.setVisible(false);
       b.setVisible(false);
       late.setVisible(false);
       absent.setVisible(false);
       pay.setVisible(false);
       ttl.setVisible(false);
       b2.setVisible(false);
       H.setVisible(false);
       hours.setVisible(false);
       this.setLocationRelativeTo(this);
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
       Date date = new Date();
       time.setText(formatter.format(date));
       showTableData();
       
       try{
     String queryaa ="SELECT * FROM mydata (pos,full_name,gender,date,age,username,pass) VALUES (?,?,?,?,?,?,?)";
     con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
     ps = con.prepareStatement(queryaa);
        ps.setString(1,Register.pos.getText());
        ps.setString(2,Register.firstname.getText()+(" ")+ Register.middlename.getText()+(" ")+Register.lastname.getText());
        ps.setString(3,Register.GENDER.getText());
        ps.setString(4,Register.month.getText() +(" ")+ Register.day.getText() +(" ")+ Register.year1.getText());
        ps.setString(5,Register.age1.getText());
        ps.setString(6,Register.username1.getText());
        ps.setString(7,Register.password1.getText());
     ps.executeUpdate();
     }catch(Exception e){
        //JOptionPane.showMessageDialog(null,"Server not connected","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void showTableData(){
         try{
      String query3="SELECT * FROM mydata";
         con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root",""); 
         ps = con.prepareStatement(query3);
         rs = ps.executeQuery();
         ey.setModel(DbUtils.resultSetToTableModel(rs) );
         }catch(Exception e ){
           JOptionPane.showMessageDialog(null,e);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cover = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        earn = new javax.swing.JTextField();
        absent = new javax.swing.JTextField();
        late = new javax.swing.JTextField();
        hehe = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pay1 = new javax.swing.JButton();
        sss = new javax.swing.JLabel();
        pag = new javax.swing.JLabel();
        phil = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        ttl = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dam = new javax.swing.JLabel();
        ad = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        absent1 = new javax.swing.JTextField();
        ca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ey = new javax.swing.JTable();
        dm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        pospos = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        position = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("SALARY EARNED:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("DEDUCTIONS:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("SSS:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("PAG-IBIG:");

        a.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        a.setText("ABSENT:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("OTHER DEDUCTIONS?");

        jButton2.setText("YES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("NO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("PHIL HEALTH:");

        b.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        b.setText("LATE:");

        pay.setText("VIEW SALARY EARN");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        earn.setText("0");
        earn.setEnabled(false);

        absent.setText("0");
        absent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absentActionPerformed(evt);
            }
        });

        late.setText("0");
        late.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lateActionPerformed(evt);
            }
        });

        hehe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        hehe.setText("TOTAL SALARY LEFT:");

        b2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        b2.setText("TTL OTHR DEDUCTION:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("TOTAL DEDUCTION:");

        pay1.setText("GENERATE PAY SLIP");
        pay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay1ActionPerformed(evt);
            }
        });

        sss.setText("420");

        pag.setText("105");

        phil.setText("100");

        total.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        b1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        b1.setText("O.T.:");

        H.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        H.setText("HOURS:");

        hours.setText("0");
        hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursActionPerformed(evt);
            }
        });

        jButton1.setText("YES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("NO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("SALARY");

        dam.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        dam.setText("DAMAGES:");

        ad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ad.setText("CASH ADVANCE:");

        a2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        a2.setText("NO.DUTY:");

        absent1.setText("0");
        absent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absent1ActionPerformed(evt);
            }
        });

        ca.setText("0");
        ca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caActionPerformed(evt);
            }
        });

        ey.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ey);

        dm.setText("0");
        dm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dmActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("NAME:");

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("POSITION:");

        h.setText("ID");

        pospos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("DATE AND TIME:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        time.setText("jLabel17");

        position.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Cashier", "Service Crew", "Cook" }));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("SAVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout coverLayout = new javax.swing.GroupLayout(cover);
        cover.setLayout(coverLayout);
        coverLayout.setHorizontalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverLayout.createSequentialGroup()
                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, coverLayout.createSequentialGroup()
                        .addComponent(H)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hours))
                    .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b2)
                        .addComponent(hehe)))
                .addGap(10, 10, 10)
                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coverLayout.createSequentialGroup()
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(coverLayout.createSequentialGroup()
                        .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(pay1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coverLayout.createSequentialGroup()
                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coverLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(a2))
                        .addGap(18, 18, 18)
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(earn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addComponent(absent1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                                .addComponent(jLabel2))))
                    .addGroup(coverLayout.createSequentialGroup()
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel4))
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(a)
                                    .addComponent(b))
                                .addGap(18, 18, 18)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(coverLayout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(coverLayout.createSequentialGroup()
                                            .addComponent(late, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(dam)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dm, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, coverLayout.createSequentialGroup()
                                            .addComponent(absent, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(ad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(coverLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(41, 41, 41)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(pag, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addGap(121, 121, 121)
                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(coverLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(coverLayout.createSequentialGroup()
                            .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(coverLayout.createSequentialGroup()
                                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pospos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(coverLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(322, 322, 322)))
                .addContainerGap())
            .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coverLayout.createSequentialGroup()
                    .addContainerGap(782, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(209, 209, 209)))
        );
        coverLayout.setVerticalGroup(
            coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coverLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coverLayout.createSequentialGroup()
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(a2)
                                    .addComponent(absent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(earn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(coverLayout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(coverLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sss, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(pag, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(phil, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pospos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(coverLayout.createSequentialGroup()
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(jButton2))
                                    .addComponent(d, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ad)
                                    .addComponent(absent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(a)
                                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b)
                                    .addComponent(late, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dam)
                                    .addComponent(dm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(coverLayout.createSequentialGroup()
                                        .addComponent(pay1)
                                        .addGap(27, 27, 27)
                                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hehe)
                                            .addComponent(pay)))
                                    .addGroup(coverLayout.createSequentialGroup()
                                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(b1)
                                            .addComponent(jButton1)
                                            .addComponent(jButton4))
                                        .addGap(34, 34, 34)
                                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(coverLayout.createSequentialGroup()
                                                .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(H)
                                                    .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(b2))
                                            .addComponent(ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButton3))
                        .addGap(221, 221, 221))
                    .addGroup(coverLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(254, 254, 254))))
            .addGroup(coverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(coverLayout.createSequentialGroup()
                    .addGap(226, 226, 226)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(632, Short.MAX_VALUE)))
        );

        jPanel1.add(cover);
        cover.setBounds(20, 0, 1250, 770);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 0, 510, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
       //if (earn.getText().equals("30")){
        
        int earned=0;
       String pos[]={"Employee","Cashier","Service Crew"};
       JComboBox position= new JComboBox(pos);
       String p=(String)position.getSelectedItem();
      if(p.equalsIgnoreCase("Employee")){
          earned=5000;
      }else if(p.equalsIgnoreCase("Cashier")){
          earned=4500;
      }else if(p.equalsIgnoreCase("Service Crew")){
          earned=4000;
      }
      String earns = String.valueOf(earned);
       earn.setText(earns);
       double ototal=0;
       double SSS= 420;
       double PAG = 105;
       double PHIL = 100;
       
       String totale = earn.getText();
       double tt= Integer.parseInt(totale);
       double t= tt-SSS;
       String x = String.valueOf(t);
       sss.setText(x);
       
       double ttt= t-PAG;
       String y = String.valueOf(ttt);
       pag.setText(y);
       
       double tttt= ttt-PHIL;
       String z = String.valueOf(tttt);
       phil.setText(z);
       
       double totald = SSS+PAG+PHIL;
       String v = String.valueOf(totald);
       d.setText(v);
       
       String A=absent.getText();
       double a = Integer.parseInt(A);
       String L = late.getText();
       double l = Integer.parseInt(L);
       String CA=ca.getText();
       double CAA=Integer.parseInt(CA);
       double CS= Double.parseDouble(CA);
       
       double ab = 50;
       double ld = 25;
       double abs = a*ab;
       double lat = l*ld;
       double al = abs+lat;
       String Total = String.valueOf(al);
       ttl.setText(Total);
       double deduction = al+totald;
     
       String hour = hours.getText();
       double ho = Integer.parseInt(hour);
       double over = 20;
       double hou = over*ho;
       double salarylefty = tt-deduction;
       double salarylefts = salarylefty+hou;      
       String dmg =dm.getText();
       double DMG= Integer.parseInt(dmg);
       double tal= salarylefts-CAA-DMG;
       String Salaryleftss = String.valueOf(tal);
       total.setText(Salaryleftss);
        
    }//GEN-LAST:event_payActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       a.setVisible(true);
       b.setVisible(true);
       late.setVisible(true);
       absent.setVisible(true);
       pay.setVisible(true);
      
       ttl.setVisible(true);
       b2.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pay.setVisible(true);
         a.setVisible(false);
       b.setVisible(false);
       late.setVisible(false);
       absent.setVisible(false);
       b2.setVisible(false);
      ttl.setVisible(false);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay1ActionPerformed
        // TODO add your handling code here:
           PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");

            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum>0){
                    return Printable.NO_SUCH_PAGE;
                }

                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.24,0.24);

                cover.paint(g2);
//          

                return Printable.PAGE_EXISTS;


            }
    });

        boolean ok = job.printDialog();
        if(ok){
        try{

        job.print();
        }
        catch (PrinterException ex){}
        }
    }//GEN-LAST:event_pay1ActionPerformed

    private void hoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        H.setVisible(true);
        hours.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void absentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absentActionPerformed

    private void lateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        H.setVisible(false);
        hours.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void absent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absent1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absent1ActionPerformed

    private void caActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caActionPerformed

    private void dmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dmActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    this.dispose();
    menu open = new menu();
    open.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void eyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyMouseClicked
        int i=ey.getSelectedRow();
        TableModel display=ey.getModel();
        h.setText(display.getValueAt(i,0).toString()); 
        pospos.setText(display.getValueAt(i,1).toString());  
        name.setText(display.getValueAt(i,2).toString());

    }//GEN-LAST:event_eyMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String names = name.getText();
        String posis = pospos.getText();
        String times = time.getText();
        String sal = total.getText();
        
        if (names.equals("") || posis.equals("") ||times.equals("") ||sal.equals("")){
            JOptionPane.showMessageDialog(null,"INVALID INPUT","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                String query = "INSERT INTO `payslip` (lname,position,date,salary) VALUES (?,?,?,?)";
                con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
                ps = con.prepareStatement(query);
                    ps.setString(1,name.getText());
                    ps.setString(2,pospos.getText());
                    ps.setString(3,time.getText());
                    ps.setString(4,total.getText());
                    ps.executeUpdate();

                JOptionPane.showMessageDialog(null,"SAVED");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Server not connected","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payslip_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payslip_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payslip_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payslip_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payslip_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel H;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a2;
    private javax.swing.JTextField absent;
    private javax.swing.JTextField absent1;
    private javax.swing.JLabel ad;
    private javax.swing.JLabel b;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JTextField ca;
    private javax.swing.JPanel cover;
    private javax.swing.JLabel d;
    private javax.swing.JLabel dam;
    private javax.swing.JTextField dm;
    private javax.swing.JTextField earn;
    private javax.swing.JTable ey;
    private javax.swing.JTextField h;
    private javax.swing.JLabel hehe;
    private javax.swing.JTextField hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField late;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pag;
    private javax.swing.JButton pay;
    private javax.swing.JButton pay1;
    private javax.swing.JLabel phil;
    private javax.swing.JComboBox position;
    private javax.swing.JLabel pospos;
    private javax.swing.JLabel sss;
    private javax.swing.JLabel time;
    private javax.swing.JLabel total;
    private javax.swing.JLabel ttl;
    // End of variables declaration//GEN-END:variables
}
