package appdev;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author lenovo
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    
    Connection con =null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    public Register() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        middlename = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        username1 = new javax.swing.JTextField();
        password1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Sgender = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        Month = new javax.swing.JComboBox();
        Date = new javax.swing.JComboBox();
        Year = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        Age = new javax.swing.JComboBox();
        Submit = new javax.swing.JButton();
        GENDER = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        month = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        day = new javax.swing.JLabel();
        age1 = new javax.swing.JLabel();
        mismatch = new javax.swing.JLabel();
        year1 = new javax.swing.JLabel();
        pospos = new javax.swing.JComboBox<>();
        pos = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ramentei Restaurant");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(289, 11, 190, 21);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rosario Cres, Lapasan, CdeO");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(270, 30, 240, 18);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 8)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cagayan De Oro City, Misamis Oriental, Philippines.");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(260, 50, 226, 12);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Register Employee:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 88, 182, 25);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Firstname:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(18, 133, 70, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Middlename:");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(18, 175, 80, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lastname:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(20, 220, 70, 16);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Username:");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(20, 260, 80, 16);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password:");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 300, 60, 16);

        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel5.add(firstname);
        firstname.setBounds(100, 130, 160, 30);
        jPanel5.add(middlename);
        middlename.setBounds(100, 170, 160, 30);
        jPanel5.add(lastname);
        lastname.setBounds(100, 210, 160, 30);

        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        jPanel5.add(username1);
        username1.setBounds(100, 250, 160, 30);

        password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password1ActionPerformed(evt);
            }
        });
        jPanel5.add(password1);
        password1.setBounds(100, 290, 160, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Sex:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(334, 133, 60, 16);

        Sgender.setBackground(new java.awt.Color(102, 102, 102));
        Sgender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "      SELECT GENDER", "FEMALE", "MALE" }));
        Sgender.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SgenderItemStateChanged(evt);
            }
        });
        Sgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SgenderActionPerformed(evt);
            }
        });
        jPanel5.add(Sgender);
        Sgender.setBounds(400, 130, 160, 22);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Birthday:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(334, 175, 60, 16);

        Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        Month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MonthItemStateChanged(evt);
            }
        });
        Month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthActionPerformed(evt);
            }
        });
        jPanel5.add(Month);
        Month.setBounds(400, 170, 90, 22);

        Date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Date.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DateItemStateChanged(evt);
            }
        });
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        jPanel5.add(Date);
        Date.setBounds(510, 170, 50, 22);

        Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970" }));
        Year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                YearItemStateChanged(evt);
            }
        });
        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });
        jPanel5.add(Year);
        Year.setBounds(590, 170, 90, 22);

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Age:");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(334, 241, 50, 16);

        Age.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));
        Age.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AgeItemStateChanged(evt);
            }
        });
        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        jPanel5.add(Age);
        Age.setBounds(404, 238, 60, 22);

        Submit.setText("SUBMIT");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel5.add(Submit);
        Submit.setBounds(130, 420, 110, 25);

        GENDER.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(GENDER);
        GENDER.setBounds(570, 130, 90, 20);

        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(290, 420, 110, 25);

        month.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(month);
        month.setBounds(400, 200, 90, 26);

        date.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(date);
        date.setBounds(487, 203, 0, 26);

        day.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(day);
        day.setBounds(510, 200, 50, 26);

        age1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(age1);
        age1.setBounds(470, 240, 50, 20);

        mismatch.setForeground(new java.awt.Color(255, 0, 0));
        jPanel5.add(mismatch);
        mismatch.setBounds(110, 330, 142, 22);

        year1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel5.add(year1);
        year1.setBounds(590, 200, 90, 26);

        pospos.setBackground(new java.awt.Color(102, 102, 102));
        pospos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POSITION", "Service Crew", "Cook", "Cashier" }));
        pospos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                posposItemStateChanged(evt);
            }
        });
        pospos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posposActionPerformed(evt);
            }
        });
        jPanel5.add(pospos);
        pospos.setBounds(200, 90, 130, 22);

        pos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(pos);
        pos.setBounds(340, 90, 90, 20);

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(450, 420, 110, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password1ActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        
    }//GEN-LAST:event_YearActionPerformed

    private void MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthActionPerformed
        String Month[];
        
    }//GEN-LAST:event_MonthActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
//        try {
//        String sql="INSERT INTO tori_table(full_name,gender,date,age,username,pass)VALUES (?,?,?,?,?,?)";
//        con = DriverManager.getConnection("jdbc;mysql;//localhost/tori","root","");
//        ps=con.prepareStatement(sql);
//        ps.setString(1,firstname.getText()+ middlename.getText()+lastname.getText());
//        ps.setString(2,GENDER.getText());
//        ps.setString(3,month.getText()+day.getText()+year1.getText());
//        ps.setString(4,age.getText());
//        ps.setString(5,username.getText());
//        ps.setString(6,password.getText());
//        ps.executeUpdate(); 
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null,"not connected");
//         }
        String posi = pos.getText();
        String fn = firstname.getText();
        String mn = middlename.getText();
        String ln = lastname.getText();
        String gens = GENDER.getText();
        String mons = month.getText();
        String dys = day.getText();
        String yrs = year1.getText();
        String edad = age1.getText();
        String user = username1.getText();
        String pass = password1.getText();
        
        
        
        if (posi.equals("") || fn.equals("") || mn.equals("")||ln.equals("")|| gens.equals("")|| mons.equals("")|| dys.equals("")|| yrs.equals("")|| edad.equals("") || user.equals("")||pass.equals("")){
            mismatch.setText("filled up all informations needed!");
        }else{
            
            try{
            String querys = "INSERT INTO `mydata`(pos,full_name,gender,date,age,username,pass) VALUES (?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            ps = con.prepareStatement(querys);
                ps.setString(1,pos.getText());
                ps.setString(2,firstname.getText()+(" ")+ middlename.getText()+(" ")+lastname.getText());
                ps.setString(3,GENDER.getText());
                ps.setString(4,month.getText() + (" ") + day.getText() + (" ") + year1.getText());
                ps.setString(5,age1.getText());
                ps.setString(6,username1.getText());
                ps.setString(7,password1.getText());
                ps.executeUpdate();

            JOptionPane.showMessageDialog(null,"SAVED");
            
            this.dispose();
            menu open = new menu();
            open.setVisible(true);
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"Server not connected","ERROR",JOptionPane.ERROR_MESSAGE);
            }
         }
       
//        try{
//        String query ="inset into mydata (pos,full_name,gender,date,age,username,pass) values (?,?,?,?,?,?,?)";
//        con = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
//        ps = con.prepareStatement(query);
//        ps.setString(1,pos.getText());
//        ps.setString(2,firstname.getText()+(" ")+ middlename.getText()+(" ")+lastname.getText());
//        ps.setString(3,GENDER.getText());
//        ps.setString(4,month.getText() +(" ")+ day.getText() +(" ")+ year1.getText());
//        ps.setString(5,age1.getText());
//        ps.setString(6,username1.getText());
//        ps.setString(7,password1.getText());
//        ps.executeUpdate();
//        
//        if (fn.equals("") || mn.equals("")||ln.equals("") || user.equals("")||pass.equals("")){
//            mismatch.setText("filled up all informations needed!");
//        }else{
//            this.dispose();
//            menu open = new menu();
//            open.setVisible(true);
//        }
//        JOptionPane.showMessageDialog(null,"SUCCESSFULLY REGISTERED");
//        }catch(Exception e){
//        JOptionPane.showMessageDialog(null,"Server not connected","ERROR",JOptionPane.ERROR_MESSAGE);
//        }
        
     
    }//GEN-LAST:event_SubmitActionPerformed

    private void SgenderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SgenderItemStateChanged
        String gender = Sgender.getSelectedItem().toString();
        GENDER.setText(gender);
    }//GEN-LAST:event_SgenderItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
       menu open=new menu();
       open.setVisible(true);
      
     
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SgenderActionPerformed

    private void MonthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MonthItemStateChanged
       String birthday = Month.getSelectedItem().toString();
        month.setText(birthday);
    }//GEN-LAST:event_MonthItemStateChanged

    private void DateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DateItemStateChanged
          String D = Date.getSelectedItem().toString();
        day.setText(D);
    }//GEN-LAST:event_DateItemStateChanged

    private void YearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_YearItemStateChanged
          String Y = Year.getSelectedItem().toString();
        year1.setText(Y);
    }//GEN-LAST:event_YearItemStateChanged

    private void AgeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AgeItemStateChanged
          String A = Age.getSelectedItem().toString();
        age1.setText(A);
    }//GEN-LAST:event_AgeItemStateChanged

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed

    private void posposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posposActionPerformed

    private void posposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_posposItemStateChanged
        String post = pospos.getSelectedItem().toString();
        pos.setText(post);
    }//GEN-LAST:event_posposItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        menu open=new menu();
        open.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox Age;
    public static javax.swing.JComboBox Date;
    public static javax.swing.JLabel GENDER;
    public static javax.swing.JComboBox Month;
    public static javax.swing.JComboBox Sgender;
    private javax.swing.JButton Submit;
    public static javax.swing.JComboBox Year;
    public static javax.swing.JLabel age1;
    public static javax.swing.JLabel date;
    public static javax.swing.JLabel day;
    public static javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JTextField lastname;
    public static javax.swing.JTextField middlename;
    public static javax.swing.JLabel mismatch;
    public static javax.swing.JLabel month;
    public static javax.swing.JTextField password1;
    public static javax.swing.JLabel pos;
    private javax.swing.JComboBox<String> pospos;
    public static javax.swing.JTextField username1;
    public static javax.swing.JLabel year1;
    // End of variables declaration//GEN-END:variables
}



